version: '2.2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data:rw,z
    # Odstraněn volume mount a reload flag pro produkci
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --workers 4