"""Initial migration

Revision ID: 2513185f0483
Revises: 
Create Date: 2025-05-02 15:19:35.814504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2513185f0483'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kurz_datum_kurzu', table_name='kurz')
    op.drop_index('ix_kurz_kod_meny', table_name='kurz')
    op.drop_index('ix_kurz_nazev_meny', table_name='kurz')
    op.drop_index('ix_kurz_nazev_statu', table_name='kurz')
    op.drop_table('kurz')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kurz',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nazev_statu', sa.VARCHAR(), nullable=False),
    sa.Column('nazev_meny', sa.VARCHAR(), nullable=False),
    sa.Column('kod_meny', sa.VARCHAR(), nullable=False),
    sa.Column('mnozstvi', sa.INTEGER(), nullable=False),
    sa.Column('kurz_meny', sa.FLOAT(), nullable=False),
    sa.Column('datum_kurzu', sa.DATE(), nullable=False),
    sa.Column('datum_create', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kurz_nazev_statu', 'kurz', ['nazev_statu'], unique=False)
    op.create_index('ix_kurz_nazev_meny', 'kurz', ['nazev_meny'], unique=False)
    op.create_index('ix_kurz_kod_meny', 'kurz', ['kod_meny'], unique=False)
    op.create_index('ix_kurz_datum_kurzu', 'kurz', ['datum_kurzu'], unique=False)
    # ### end Alembic commands ###
